{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "ImageStream",
            "metadata": {
                "labels": {
                    "app": "myapp",
                    "template": "java-promotion-template"
                },
                "name": "myapp"
            },
            "spec": {},
            "status": {
                "dockerImageRepository": ""
            }
        },
        {
            "apiVersion": "v1",
            "kind": "BuildConfig",
            "metadata": {
                "annotations": {
                    "pipeline.alpha.openshift.io/uses": "[{\"name\": \"myapp\", \"namespace\": \"\", \"kind\": \"DeploymentConfig\"}]"
                },
                "labels": {
                    "app": "myapp",
                    "template": "java-promotion-template"
                },
                "name": "myapp"
            },
            "spec": {
                "output": {},
                "postCommit": {},
                "resources": {},
                "runPolicy": "Serial",
                "source": {
                    "contextDir": "",
                    "git": {
                        "ref": "prod",
                        "uri": "https://github.com/victornc83/sb-base.git"
                    },
                    "type": "Git"
                },
                "strategy": {
                    "jenkinsPipelineStrategy": {
                        "jenkinsfilePath": "jenkinsfile"
                    },
                    "type": "JenkinsPipeline"
                },
                "triggers": [
                    {
                        "github": {
                            "secret": "L4WX6Fw6"
                        },
                        "type": "GitHub"
                    },
                    {
                        "generic": {
                            "secret": "ErcR8HI6"
                        },
                        "type": "Generic"
                    },
                    {
                        "imageChange": {},
                        "type": "ImageChange"
                    }
                ]
            }
        },
        {
            "apiVersion": "v1",
            "kind": "DeploymentConfig",
            "metadata": {
                "labels": {
                    "app": "myapp",
                    "template": "java-promotion-template"
                },
                "name": "myapp"
            },
            "spec": {
                "replicas": 1,
                "selector": {
                    "app": "myapp"
                },
                "strategy": {
                    "rollingParams": {
                        "intervalSeconds": 1,
                        "maxSurge": "25%",
                        "maxUnavailable": "25%",
                        "timeoutSeconds": 600,
                        "updatePeriodSeconds": 1
                    },
                    "type": "Rolling"
                },
                "template": {
                    "metadata": {
                        "labels": {
                            "app": "myapp",
                            "deploymentconfig": "myapp"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "env": [
                                    {
                                        "name": "APPLICATION_HOSTNAME",
                                        "value": ""
                                    }
                                ],
                                "image": "myapp:0.1-SNAPSHOT",
                                "imagePullPolicy": "Always",
                                "livenessProbe": {
                                    "failureThreshold": 3,
                                    "httpGet": {
                                        "path": "/",
                                        "port": 8080,
                                        "scheme": "HTTP"
                                    },
                                    "initialDelaySeconds": 30,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "timeoutSeconds": 2
                                },
                                "name": "myapp",
                                "ports": [
                                    {
                                        "containerPort": 8080,
                                        "protocol": "TCP"
                                    }
                                ],
                                "readinessProbe": {
                                    "failureThreshold": 3,
                                    "httpGet": {
                                        "path": "/",
                                        "port": 8080,
                                        "scheme": "HTTP"
                                    },
                                    "initialDelaySeconds": 30,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "timeoutSeconds": 2
                                },
                                "resources": {},
                                "terminationMessagePath": "/dev/termination-log"
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Always",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30
                    }
                },
                "test": false,
                "triggers": [
                    {
                        "type": "ConfigChange"
                    },
                    {
                        "imageChangeParams": {
                            "automatic": true,
                            "containerNames": [
                                "myapp"
                            ],
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "myapp:0.1-SNAPSHOT"
                            }
                        },
                        "type": "ImageChange"
                    }
                ]
            },
            "status": {}
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftNewApp"
                },
                "labels": {
                    "app": "myapp",
                    "template": "java-promotion-template"
                },
                "name": "myapp"
            },
            "spec": {
                "ports": [
                    {
                        "name": "8080-tcp",
                        "port": 8080,
                        "protocol": "TCP",
                        "targetPort": 8080
                    }
                ],
                "selector": {
                    "app": "myapp",
                    "deploymentconfig": "myapp"
                },
                "sessionAffinity": "None",
                "type": "ClusterIP"
            },
            "status": {
                "loadBalancer": {}
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Route",
            "metadata": {
                "labels": {
                    "app": "myapp",
                    "template": "java-promotion-template"
                },
                "name": "myapp"
            },
            "spec": {
                "host": "",
                "port": {
                    "targetPort": "8080-tcp"
                },
                "to": {
                    "kind": "Service",
                    "name": "myapp",
                    "weight": 100
                },
                "wildcardPolicy": "None"
            }
        }
    ]
}
